$defs:
  AccessLevel:
    description: "Access level for tools to manage read/write operations.\n\nLevels:\n\
      \    READ: Tool only reads state, no side effects\n    WRITE: Tool modifies\
      \ state or has side effects (default)\n    ADMIN: Tool has system-level access\
      \ (fork, spawn, goto)"
    enum:
    - read
    - write
    - admin
    title: AccessLevel
    type: string
  AnthropicToolsConfig:
    description: Anthropic provider-specific tools configuration.
    properties:
      web_search:
        anyOf:
        - $ref: '#/$defs/AnthropicWebSearchConfig'
        - type: 'null'
        default: null
    title: AnthropicToolsConfig
    type: object
  AnthropicWebSearchConfig:
    description: Anthropic web search tool configuration.
    properties:
      enabled:
        default: false
        title: Enabled
        type: boolean
      max_uses:
        anyOf:
        - maximum: 50
          minimum: 1
          type: integer
        - type: 'null'
        default: null
        description: Max searches per request
        title: Max Uses
      allowed_domains:
        anyOf:
        - items:
            type: string
          type: array
        - type: 'null'
        default: null
        description: Whitelist of allowed domains
        title: Allowed Domains
      blocked_domains:
        anyOf:
        - items:
            type: string
          type: array
        - type: 'null'
        default: null
        description: Blacklist of blocked domains
        title: Blocked Domains
      user_location:
        anyOf:
        - additionalProperties: true
          type: object
        - type: 'null'
        default: null
        title: User Location
    title: AnthropicWebSearchConfig
    type: object
  DemoConfig:
    description: Demo configuration for multi-turn demonstrations.
    properties:
      prompts:
        default: []
        items:
          type: string
        title: Prompts
        type: array
      pause_between_prompts:
        default: true
        title: Pause Between Prompts
        type: boolean
    title: DemoConfig
    type: object
  EnvInfoPluginConfig:
    additionalProperties: true
    description: Configuration for the environment info plugin.
    properties:
      variables:
        items:
          type: string
        title: Variables
        type: array
    title: EnvInfoPluginConfig
    type: object
  FileDescriptorPluginConfig:
    description: Configuration for the file descriptor plugin.
    properties:
      max_direct_output_chars:
        default: 8000
        title: Max Direct Output Chars
        type: integer
      default_page_size:
        default: 4000
        title: Default Page Size
        type: integer
      max_input_chars:
        default: 8000
        title: Max Input Chars
        type: integer
      page_user_input:
        default: true
        title: Page User Input
        type: boolean
      enable_references:
        default: false
        title: Enable References
        type: boolean
      tools:
        items:
          anyOf:
          - type: string
          - $ref: '#/$defs/ToolConfig'
        title: Tools
        type: array
    title: FileDescriptorPluginConfig
    type: object
  MCPConfig:
    description: MCP configuration section.
    properties:
      config_path:
        anyOf:
        - type: string
        - type: 'null'
        default: null
        title: Config Path
      servers:
        anyOf:
        - additionalProperties:
            additionalProperties: true
            type: object
          type: object
        - type: 'null'
        default: null
        title: Servers
    title: MCPConfig
    type: object
  MCPToolsConfig:
    additionalProperties:
      anyOf:
      - const: all
        type: string
      - items:
          anyOf:
          - type: string
          - $ref: '#/$defs/ToolConfig'
          - additionalProperties: true
            type: object
        type: array
    default: {}
    description: "MCP tools configuration.\n\nThis provides a simplified configuration\
      \ model for MCP tools with four supported formats:\n\n1. \"all\" - Include all\
      \ tools from a server\n   example = \"all\"\n\n2. List of tool names - Include\
      \ specific tools with default access\n   example = [\"tool1\", \"tool2\"]\n\n\
      3. List of ToolConfig objects - Include specific tools with custom access\n\
      \   example = [\n       ToolConfig(name=\"tool1\", access=AccessLevel.READ),\n\
      \       ToolConfig(name=\"tool2\")\n   ]\n4. Dictionary of tool names to access/description\
      \ dictionaries\n   example = {\n       \"tool1\": {\"access\": \"read\", \"\
      description\": \"Custom desc\"},\n       \"tool2\": {\"description\": \"Another\
      \ desc\"}\n   }"
    title: MCPToolsConfig
    type: object
  MessageIDPluginConfig:
    description: Configuration for the message ID plugin.
    properties:
      enable_goto:
        default: true
        title: Enable Goto
        type: boolean
      tools:
        items:
          anyOf:
          - type: string
          - $ref: '#/$defs/ToolConfig'
        title: Tools
        type: array
    title: MessageIDPluginConfig
    type: object
  ModelConfig:
    description: Model configuration section.
    properties:
      name:
        title: Name
        type: string
      provider:
        title: Provider
        type: string
      project_id:
        anyOf:
        - type: string
        - type: 'null'
        default: null
        title: Project Id
      region:
        anyOf:
        - type: string
        - type: 'null'
        default: null
        title: Region
      max_iterations:
        default: 10
        title: Max Iterations
        type: integer
    required:
    - name
    - provider
    title: ModelConfig
    type: object
  OpenAIToolsConfig:
    description: OpenAI provider-specific tools configuration.
    properties:
      web_search:
        anyOf:
        - $ref: '#/$defs/OpenAIWebSearchConfig'
        - type: 'null'
        default: null
    title: OpenAIToolsConfig
    type: object
  OpenAIWebSearchConfig:
    description: OpenAI web search tool configuration.
    properties:
      enabled:
        default: false
        title: Enabled
        type: boolean
      search_context_size:
        default: medium
        description: How much context to include in search (low/medium/high)
        title: Search Context Size
        type: string
      user_location:
        anyOf:
        - additionalProperties: true
          type: object
        - type: 'null'
        default: null
        title: User Location
    title: OpenAIWebSearchConfig
    type: object
  ParameterConfig:
    additionalProperties: true
    description: Validated LLM API parameters.
    properties:
      temperature:
        anyOf:
        - type: number
        - type: 'null'
        default: null
        title: Temperature
      max_tokens:
        anyOf:
        - type: integer
        - type: 'null'
        default: null
        title: Max Tokens
      top_p:
        anyOf:
        - type: number
        - type: 'null'
        default: null
        title: Top P
      frequency_penalty:
        anyOf:
        - type: number
        - type: 'null'
        default: null
        title: Frequency Penalty
      presence_penalty:
        anyOf:
        - type: number
        - type: 'null'
        default: null
        title: Presence Penalty
      top_k:
        anyOf:
        - type: integer
        - type: 'null'
        default: null
        title: Top K
      stop:
        anyOf:
        - items:
            type: string
          type: array
        - type: string
        - type: 'null'
        default: null
        title: Stop
      reasoning_effort:
        anyOf:
        - type: string
        - type: 'null'
        default: null
        title: Reasoning Effort
      max_completion_tokens:
        anyOf:
        - type: integer
        - type: 'null'
        default: null
        title: Max Completion Tokens
      max_tokens_to_sample:
        anyOf:
        - type: integer
        - type: 'null'
        default: null
        title: Max Tokens To Sample
      stop_sequences:
        anyOf:
        - items:
            type: string
          type: array
        - type: string
        - type: 'null'
        default: null
        title: Stop Sequences
      thinking:
        anyOf:
        - $ref: '#/$defs/ThinkingConfig'
        - type: 'null'
        default: null
      extra_headers:
        anyOf:
        - additionalProperties: true
          type: object
        - type: 'null'
        default: null
        title: Extra Headers
    title: ParameterConfig
    type: object
  PluginsConfig:
    additionalProperties: true
    description: Root model for plugin configurations.
    properties:
      file_descriptor:
        anyOf:
        - $ref: '#/$defs/FileDescriptorPluginConfig'
        - type: 'null'
        default: null
      message_id:
        anyOf:
        - $ref: '#/$defs/MessageIDPluginConfig'
        - type: 'null'
        default: null
      spawn:
        anyOf:
        - $ref: '#/$defs/SpawnPluginConfig'
        - type: 'null'
        default: null
      stderr:
        anyOf:
        - $ref: '#/$defs/StderrPluginConfig'
        - type: 'null'
        default: null
      preload_files:
        anyOf:
        - $ref: '#/$defs/PreloadFilesPluginConfig'
        - type: 'null'
        default: null
      env_info:
        anyOf:
        - $ref: '#/$defs/EnvInfoPluginConfig'
        - type: 'null'
        default: null
    title: PluginsConfig
    type: object
  PreloadFilesPluginConfig:
    description: Configuration for the preload files plugin.
    properties:
      files:
        items:
          type: string
        title: Files
        type: array
      relative_to:
        default: program
        enum:
        - program
        - cwd
        title: Relative To
        type: string
    title: PreloadFilesPluginConfig
    type: object
  PromptConfig:
    description: Prompt configuration section.
    properties:
      system:
        anyOf:
        - type: string
        - type: 'null'
        default: ''
        title: System
      system_prompt_file:
        anyOf:
        - type: string
        - type: 'null'
        default: null
        title: System Prompt File
      user_prompt:
        anyOf:
        - type: string
        - type: 'null'
        default: null
        title: User Prompt
    title: PromptConfig
    type: object
  SpawnPluginConfig:
    description: Configuration for the spawn plugin.
    properties:
      linked_programs:
        additionalProperties:
          type: string
        title: Linked Programs
        type: object
      linked_program_descriptions:
        additionalProperties:
          type: string
        title: Linked Program Descriptions
        type: object
      tools:
        items:
          anyOf:
          - type: string
          - $ref: '#/$defs/ToolConfig'
        title: Tools
        type: array
    title: SpawnPluginConfig
    type: object
  StderrPluginConfig:
    description: Configuration for the stderr logging plugin.
    properties:
      tools:
        items:
          anyOf:
          - type: string
          - $ref: '#/$defs/ToolConfig'
        title: Tools
        type: array
    title: StderrPluginConfig
    type: object
  ThinkingConfig:
    description: Configuration for Claude 3.7 thinking capability.
    properties:
      type:
        default: enabled
        enum:
        - enabled
        - disabled
        title: Type
        type: string
      budget_tokens:
        anyOf:
        - type: integer
        - type: 'null'
        default: null
        title: Budget Tokens
    title: ThinkingConfig
    type: object
  ToolConfig:
    description: Configuration item for a tool.
    properties:
      name:
        title: Name
        type: string
      alias:
        anyOf:
        - type: string
        - type: 'null'
        default: null
        title: Alias
      description:
        anyOf:
        - type: string
        - type: 'null'
        default: null
        title: Description
      access:
        $ref: '#/$defs/AccessLevel'
        default: write
      param_descriptions:
        anyOf:
        - additionalProperties:
            type: string
          type: object
        - type: 'null'
        default: null
        title: Param Descriptions
    required:
    - name
    title: ToolConfig
    type: object
  ToolsConfig:
    description: Tools configuration section.
    properties:
      builtin:
        items:
          anyOf:
          - type: string
          - $ref: '#/$defs/ToolConfig'
        title: Builtin
        type: array
      mcp:
        anyOf:
        - $ref: '#/$defs/MCPToolsConfig'
        - type: 'null'
        default: null
      anthropic:
        anyOf:
        - $ref: '#/$defs/AnthropicToolsConfig'
        - type: 'null'
        default: null
      openai:
        anyOf:
        - $ref: '#/$defs/OpenAIToolsConfig'
        - type: 'null'
        default: null
    title: ToolsConfig
    type: object
additionalProperties: true
description: Full LLM program configuration.
properties:
  model:
    $ref: '#/$defs/ModelConfig'
  prompt:
    $ref: '#/$defs/PromptConfig'
    default:
      system: ''
      system_prompt_file: null
      user_prompt: null
  parameters:
    $ref: '#/$defs/ParameterConfig'
  mcp:
    anyOf:
    - $ref: '#/$defs/MCPConfig'
    - type: 'null'
    default: null
  tools:
    anyOf:
    - $ref: '#/$defs/ToolsConfig'
    - type: 'null'
    default:
      builtin: []
      mcp: null
      anthropic: null
      openai: null
  plugins:
    anyOf:
    - $ref: '#/$defs/PluginsConfig'
    - type: 'null'
    default: null
  demo:
    anyOf:
    - $ref: '#/$defs/DemoConfig'
    - type: 'null'
    default: null
required:
- model
title: LLMProgramConfig
type: object
